# Generated by Django 2.1.7 on 2019-05-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
