# Generated by Django 2.1.7 on 2019-05-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_panel', '0002_lesson_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
