# Generated by Django 2.1.7 on 2019-05-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_panel', '0003_auto_20190512_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('1', 'Pon'), ('2', 'Wt'), ('4', 'Śr'), ('4', 'Czw'), ('5', 'Pt'), ('6', 'Sob'), ('7', 'Nie')], default=None, max_length=20),
        ),
    ]
