# Generated by Django 2.1.7 on 2019-05-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20190324_2058'),
        ('lessons_panel', '0004_auto_20190512_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('1', 'Pon'), ('2', 'Wt'), ('3', 'Śr'), ('4', 'Czw'), ('5', 'Pt'), ('6', 'Sob'), ('7', 'Nie')], default=None, max_length=20),
        ),
    ]
