# Generated by Django 2.1.5 on 2019-03-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial_migrate'),
        ('classes_app', '0001_initial_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('class_field', models.ForeignKey(db_column='class_ID', on_delete=django.db.models.deletion.CASCADE, to='classes_app.Class')),
                ('school', models.ForeignKey(db_column='school_ID', on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
            options={
                'db_table': 'schedule',
                'managed': True,
            },
        ),
    ]
