# Generated by Django 2.1.7 on 2019-03-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20190324_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='class_field',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='classes_app.Class'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
    ]
