# Generated by Django 2.1.7 on 2019-03-27 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20190324_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
    ]
