# Generated by Django 2.1.7 on 2019-03-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_schedule_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
