# Generated by Django 2.1.7 on 2019-03-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20190327_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
