# Generated by Django 2.1.7 on 2019-03-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20190327_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='year',
        ),
    ]
