# Generated by Django 2.1.7 on 2019-03-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_schedule_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='year',
        ),
    ]
