# Generated by Django 2.1.7 on 2019-04-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_schedule_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=None)),
            ],
            options={
                'db_table': 'schedule_date',
                'managed': True,
            },
        ),
    ]
