# Generated by Django 2.1.7 on 2019-04-27 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_scheduledate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.ScheduleDate'),
        ),
    ]
