# Generated by Django 2.1.7 on 2019-04-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_auto_20190428_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterModelTable(
            name='scheduledate',
            table='schedule',
        ),
    ]
