# Generated by Django 2.1.7 on 2019-04-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_auto_20190428_0115'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scheduledate',
            table='schedule_date',
        ),
    ]
