# Generated by Django 2.1.7 on 2019-04-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0016_auto_20190428_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='year',
            new_name='schedule_date',
        ),
    ]
