# Generated by Django 2.1.7 on 2019-04-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0017_auto_20190428_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_date',
            new_name='year',
        ),
    ]
