# Generated by Django 2.1.5 on 2019-03-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0001_initial_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
