# Generated by Django 2.2.1 on 2019-05-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0005_remove_class_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='short_name',
            field=models.CharField(max_length=40),
        ),
    ]
