# Generated by Django 2.1.5 on 2019-01-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('short_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
    ]
