# Generated by Django 2.1.3 on 2018-11-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('short_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='start_page.Class')),
            ],
            options={
                'db_table': 'class_group',
            },
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tutor', models.IntegerField()),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='start_page.Class')),
            ],
            options={
                'db_table': 'class_teacher',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('lesson_number', models.IntegerField()),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='start_page.Class')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_page.Group')),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('cycle', models.IntegerField()),
                ('school_year', models.CharField(max_length=45)),
                ('school_name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('weekend_days', models.CharField(max_length=45)),
                ('start_time', models.CharField(max_length=45)),
                ('max_lessons', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_page.AuthUser')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='SchoolBreakes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('lesson_number', models.IntegerField()),
                ('break_time', models.IntegerField()),
                ('schedule', models.ForeignKey(db_column='schedule_ID', on_delete=django.db.models.deletion.CASCADE, to='start_page.Schedule')),
            ],
            options={
                'db_table': 'school_breakes',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=45, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(db_column='schedule_ID', on_delete=django.db.models.deletion.CASCADE, to='start_page.Schedule')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('schedule', models.ForeignKey(db_column='schedule_ID', on_delete=django.db.models.deletion.CASCADE, to='start_page.Schedule')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='TeacherLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_page.Lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_page.Teacher')),
            ],
            options={
                'db_table': 'teacher_lesson',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(db_column='subject_ID', on_delete=django.db.models.deletion.CASCADE, to='start_page.Subject')),
                ('teacher', models.ForeignKey(db_column='teacher_ID', on_delete=django.db.models.deletion.CASCADE, to='start_page.Teacher')),
            ],
            options={
                'db_table': 'teacher_subject',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='schedule',
            field=models.ForeignKey(db_column='schedule_ID', on_delete=django.db.models.deletion.CASCADE, to='start_page.Schedule'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(db_column='room_ID', on_delete=django.db.models.deletion.CASCADE, to='start_page.Room'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(db_column='subject_ID', on_delete=django.db.models.deletion.CASCADE, to='start_page.Subject'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_page.Teacher'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_page.Group'),
        ),
        migrations.AddField(
            model_name='class',
            name='schedule',
            field=models.ForeignKey(db_column='schedule_ID', on_delete=django.db.models.deletion.CASCADE, to='start_page.Schedule'),
        ),
    ]
