# Generated by Django 2.1.2 on 2018-11-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
        migrations.AlterModelOptions(
            name='classgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='classteacher',
            options={},
        ),
        migrations.AlterModelOptions(
            name='schoolbreakes',
            options={},
        ),
    ]
