# Generated by Django 2.1.3 on 2018-11-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0002_auto_20181113_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
