# Generated by Django 2.1.3 on 2018-11-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0003_auto_20181122_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
