# Generated by Django 2.1.3 on 2018-11-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0005_auto_20181122_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_favorite',
        ),
    ]
