# Generated by Django 2.1.5 on 2019-03-13 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_year', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('weekend_days', models.CharField(max_length=45)),
                ('start_time', models.CharField(max_length=20)),
                ('max_lessons', models.IntegerField()),
                ('cycle', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'school',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SchoolBreakes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_number', models.IntegerField()),
                ('break_time', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
            options={
                'db_table': 'school_breakes',
                'managed': True,
            },
        ),
    ]
