# Generated by Django 2.1.5 on 2019-01-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('school_year', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('weekend_days', models.CharField(max_length=45)),
                ('start_time', models.CharField(max_length=20)),
                ('max_lessons', models.IntegerField()),
                ('cycle', models.IntegerField()),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolBreakes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('lesson_number', models.IntegerField()),
                ('break_time', models.IntegerField()),
            ],
            options={
                'db_table': 'school_breakes',
                'managed': False,
            },
        ),
    ]
