# Generated by Django 2.1.7 on 2019-03-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20190324_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_year',
        ),
    ]
