# Generated by Django 2.2.1 on 2019-05-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_remove_school_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='cycle',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
