# Generated by Django 2.2.1 on 2019-05-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20190527_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='weekend_days',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
    ]
